export const FETCH_HEROES_REQUEST = 'FETCH_HEROES_REQUEST';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
export const FETCH_HEROES_FAILURE = 'FETCH_HEROES_FAILURE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const SEARCH_HEROES = 'SEARCH_HEROES';
export const NEXT_HEROES = 'NEXT_HEROES';
export const LAST_HEROES = 'LAST_HEROES';
export const CHANGE_FILTER = 'CHANGE_FILTER';
